// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0cLawOBHDaYmc884d42KZblb_LYHfaDo',
    appId: '1:1027474286088:web:85f348db59514dec8c53bd',
    messagingSenderId: '1027474286088',
    projectId: 'loginpage-cbea9',
    authDomain: 'loginpage-cbea9.firebaseapp.com',
    storageBucket: 'loginpage-cbea9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8xezM30Yz_7dujvMt5sHioxnIAr1yc_c',
    appId: '1:1027474286088:android:43a4a6e8d9bc45bc8c53bd',
    messagingSenderId: '1027474286088',
    projectId: 'loginpage-cbea9',
    storageBucket: 'loginpage-cbea9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr76g_MDP-4qI59Gc0ro8_cKVDMleDKSE',
    appId: '1:1027474286088:ios:51f47605e4bfae148c53bd',
    messagingSenderId: '1027474286088',
    projectId: 'loginpage-cbea9',
    storageBucket: 'loginpage-cbea9.appspot.com',
    iosClientId: '1027474286088-l6fb4604id8gfu0d06daqtc06nsh1cbu.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr76g_MDP-4qI59Gc0ro8_cKVDMleDKSE',
    appId: '1:1027474286088:ios:51f47605e4bfae148c53bd',
    messagingSenderId: '1027474286088',
    projectId: 'loginpage-cbea9',
    storageBucket: 'loginpage-cbea9.appspot.com',
    iosClientId: '1027474286088-l6fb4604id8gfu0d06daqtc06nsh1cbu.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginpage',
  );
}
